module.exports = [
    './gulp/tasks/sass.js',
    './gulp/tasks/pug.js',
    './gulp/tasks/del.js',
    './gulp/tasks/watch.js',
    './gulp/tasks/sprite.svg.js',
    './gulp/tasks/js.js',
    './gulp/tasks/imagescopy.js',
    './gulp/tasks/fontscopy.js',
    './gulp/tasks/jscopy.js',
    './gulp/tasks/iconscopy.js',
    './gulp/tasks/phpcopy.js',
    './gulp/tasks/images.js',
    './gulp/tasks/serve.js',
    './gulp/tasks/spritescopy.js',
];
